version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "installing something"
            - npm install -g yarn
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
            - yarn install
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - yarn build
    post_build:
        commands:
            - echo "we are in the post build phase"
artifacts:
    files:
        - '**/*'
    base-directory: dist
